---
# This playbook installs Docker

- name: Setup proper hostname
  hostname: name=docker-vm

- name: Install Docker packages
  dnf: >
    name={{ item }}
    state=latest
  with_items:
    - docker-io
    - python-docker-py

- name: Create docker group
  group:
    name=docker
    state=present

- name: Enable docker service
  service:
    name=docker
    enabled=yes

#- name: Switch to OverlayFS storage backend
#  lineinfile:
#    dest=/etc/sysconfig/docker-storage
#    state=present
#    regexp="^DOCKER_STORAGE_OPTIONS=(.*)(--storage-driver=.*\s*)*(.*)$"
#    line='DOCKER_STORAGE_OPTIONS=\1 --storage-driver=overlay \3'
#    backrefs=yes

- name: Restart Docker service
  service:
    name=docker
    state=restarted